# Generated by Django 4.0.6 on 2022-09-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_postmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='post_view',
            field=models.IntegerField(default=0),
        ),
    ]
