# Generated by Django 4.0.6 on 2022-09-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_postmodel_post_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
